kind: pipeline
name: Build and Test Frontend
type: docker

steps:
  - name: build
    image: docker:latest
    commands:
      - docker build --no-cache -t directcuteo/mina-frontend:latest -f Dockerfile2 .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

  - name: frontend-server
    image: directcuteo/mina-frontend:latest
    pull: if-not-exists
    detach: true
    privileged: true
    depends_on:
      - build

  - name: prepare-tests
    image: cypress/included:12.6.0
    commands:
      - npm install
    depends_on:
      - build

  - name: dashboard-nodes-table
    image: cypress/included:12.6.0
    commands:
      - cypress run --config-file "cypress.config.js" --spec "cypress/e2e/dashboard/nodes/dashboard-nodes-table.cy.ts"
    depends_on:
      - prepare-tests

  - name: dashboard-nodes-toolbar
    image: cypress/included:12.6.0
    commands:
      - cypress run --config-file "cypress.config.js" --spec "cypress/e2e/dashboard/nodes/dashboard-nodes-toolbar.cy.ts"
    depends_on:
      - prepare-tests

  - name: network-messages-table
    image: cypress/included:12.6.0
    commands:
      - cypress run --config-file "cypress.config.js" --spec "cypress/e2e/network/messages/network-messages-table.cy.ts"
    depends_on:
      - prepare-tests

  - name: network-blocks-table
    image: cypress/included:12.6.0
    commands:
      - cypress run --config-file "cypress.config.js" --spec "cypress/e2e/network/blocks/network-blocks-table.cy.ts"
    depends_on:
      - prepare-tests

  - name: network-blocks-toolbar
    image: cypress/included:12.6.0
    commands:
      - cypress run --config-file "cypress.config.js" --spec "cypress/e2e/network/blocks/network-blocks-toolbar.cy.ts"
    depends_on:
      - prepare-tests

  - name: network-blocks-ipc-table
    image: cypress/included:12.6.0
    commands:
      - cypress run --config-file "cypress.config.js" --spec "cypress/e2e/network/blocks-ipc/network-blocks-ipc-table.cy.ts"
    depends_on:
      - prepare-tests

image_pull_secrets:
  - docker_pull_secret

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - local
  event: push
