export enum Routes {
  NETWORK = 'network',
  MESSAGES = 'messages',
  CONNECTIONS = 'connections',
  TRACING = 'tracing',
  BLOCKS = 'blocks',
  OVERVIEW = 'overview',
  WEB_NODE = 'web-node',
  LOGS = 'logs',
  PEERS = 'peers',
  WALLET = 'wallet',
  STATE = 'state',
  WALLETS = 'wallets',
  TRANSACTIONS = 'transactions',
  SNARKS = 'snarks',
  DASHBOARD = 'dashboard',
  BLOCKS_IPC = 'blocks-ipc',
  BLOCK = 'block',
  LIBP2P = 'libp2p',
  NODES = 'nodes',
  SCAN_STATE = 'scan-state',
  EXPLORER = 'explorer',
}
