/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_manualconnector_free(a: number): void;
export function manualconnector_dial(a: number, b: number, c: number, d: number): void;
export function manualconnector_listen(a: number): number;
export function __wbg_jshandle_free(a: number): void;
export function jshandle_manual_connector(a: number): number;
export function jshandle_is_peer_id_valid(a: number, b: number, c: number, d: number): void;
export function jshandle_peer_disconnect(a: number, b: number, c: number): number;
export function jshandle_request_send_message(a: number, b: number): void;
export function jshandle_generate_account_keys(a: number): number;
export function jshandle_payment_sign_and_inject(a: number, b: number, c: number): void;
export function start(a: number): number;
export function __wbg_crypto_free(a: number): void;
export function crypto_pub_key_as_protobuf(a: number, b: number): void;
export function crypto_peer_id_as_b58(a: number, b: number): void;
export function crypto_sign(a: number, b: number, c: number, d: number): void;
export function crypto_pub_key_as_protobuf_to_peer_id_as_b58(a: number, b: number, c: number, d: number): void;
export function crypto_assert_signature(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function crypto_pub_key_as_protobuf_to_peer_id(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h3bb6f667c6ce1a91(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hc065c0a1b513a5a2(a: number, b: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h99dcb8ea1aa8cd83(a: number, b: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h3c65b2aab8dcbcaa(a: number, b: number, c: number, d: number): void;
