/* tslint:disable */
/* eslint-disable */
export function __wbg_inmemlog_free(a: number): void;
export function inmemlog_get(a: number, b: number, c: number, d: number): void;
export function inmemlog_id(a: number): number;
export function inmemlog_level(a: number): number;
export function inmemlog_as_json(a: number, b: number): void;
export function __wbg_manualconnector_free(a: number): void;
export function manualconnector_dial(a: number, b: number, c: number): number;
export function manualconnector_listen(a: number): number;
export function __wbg_wasmconfig_free(a: number): void;
export function wasmconfig_new(): number;
export function wasmconfig_set_block_verifier_index(a: number, b: number): void;
export function wasmconfig_set_block_verifier_srs(a: number, b: number): void;
export function start(a: number): number;
export function __wbg_jshandle_free(a: number): void;
export function jshandle_logs_range(a: number, b: number, c: number, d: number, e: number): number;
export function jshandle_manual_connector(a: number): number;
export function jshandle_is_peer_id_valid(a: number, b: number, c: number, d: number): void;
export function jshandle_is_account_pk_valid(a: number, b: number, c: number, d: number): void;
export function jshandle_global_state_get(a: number): number;
export function jshandle_action_stats_since_start_get(a: number): number;
export function jshandle_best_tip_summary(a: number): number;
export function jshandle_peer_connect(a: number, b: number, c: number): number;
export function jshandle_pubsub_publish(a: number, b: number, c: number, d: number): number;
export function jshandle_generate_account_keys(a: number): number;
export function jshandle_payment_sign_and_inject(a: number, b: number): number;
export function jshandle_watched_accounts(a: number): number;
export function __wbg_watchedaccounts_free(a: number): void;
export function watchedaccounts_add(a: number, b: number, c: number): number;
export function watchedaccounts_get(a: number, b: number, c: number): number;
export function wasm_thread_entry_point(a: number): void;
export function __wbg_crypto_free(a: number): void;
export function crypto_pub_key_as_protobuf(a: number, b: number): void;
export function crypto_peer_id_as_b58(a: number, b: number): void;
export function crypto_sign(a: number, b: number, c: number, d: number): void;
export function crypto_pub_key_as_protobuf_to_peer_id_as_b58(a: number, b: number, c: number, d: number): void;
export function crypto_assert_signature(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function crypto_pub_key_as_protobuf_to_peer_id(a: number, b: number, c: number, d: number, e: number, f: number): void;
export const memory: WebAssembly.Memory;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_3: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut___A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hf6095eaffb8acc8e(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h7e766a04a1afb3ee(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h49dccfef7a303cdb(a: number, b: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h1ace8829c1af1eec(a: number, b: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h16dafbe231267050(a: number, b: number, c: number, d: number): void;
export function __wbindgen_thread_destroy(): void;
export function __wbindgen_start(): void;
